// <auto-generated />
namespace QLCuaHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Dongia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Dongia));
        
        string IMigrationMetadata.Id
        {
            get { return "202012110924077_add_Dongia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
