// <auto-generated />
namespace QLCuaHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NhapKho_CT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NhapKho_CT));
        
        string IMigrationMetadata.Id
        {
            get { return "202012110222310_NhapKho_CT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
