// <auto-generated />
namespace QLCuaHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_role_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_role_column));
        
        string IMigrationMetadata.Id
        {
            get { return "202012110847067_add_role_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
